version: '3.9'
services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/django/static
      - ./nginx/cert:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  app:
    build: .
    volumes:
      - .:/django
      - static_volume:/django/static
    image: app:django
    container_name: django_container
    env_file:
      - ./.env.prod
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn gallery_service.wsgi:application --bind 0.0.0.0:8000"

volumes:
  static_volume:


