# Generated by Django 4.1.1 on 2022-09-10 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0003_artistmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="작품명")),
                ("size", models.CharField(max_length=200, verbose_name="사이즈")),
                (
                    "number",
                    models.IntegerField(default=0, max_length=4, verbose_name="호수"),
                ),
                ("price", models.IntegerField(default=0, verbose_name="가격")),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arts_names",
                        to="user.artistmodel",
                    ),
                ),
            ],
            options={"db_table": "art",},
        ),
    ]
