# Generated by Django 4.1.1 on 2022-09-10 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_artistmodel"),
        ("art", "0002_alter_artmodel_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artmodel",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arts",
                to="user.artistmodel",
            ),
        ),
        migrations.CreateModel(
            name="ExhibitionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="전시회명")),
                (
                    "art_list",
                    models.ManyToManyField(
                        blank=True,
                        related_name="exhibition",
                        to="art.artmodel",
                        verbose_name="작품리스트",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.artistmodel",
                    ),
                ),
            ],
            options={"db_table": "exhibition",},
        ),
    ]
