# Generated by Django 4.1.1 on 2022-09-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0004_exhibitionmodel_end_date_exhibitionmodel_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="artmodel",
            name="image",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
    ]
