# Generated by Django 4.1.1 on 2022-09-10 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0005_artmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="artmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
