# Generated by Django 4.1.1 on 2022-09-11 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0006_artmodel_created_at_artmodel_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artmodel",
            name="name",
            field=models.CharField(max_length=64, verbose_name="작품명"),
        ),
        migrations.AlterField(
            model_name="artmodel",
            name="number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="호수",
            ),
        ),
        migrations.AlterField(
            model_name="artmodel",
            name="price",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="가격",
            ),
        ),
        migrations.AlterField(
            model_name="exhibitionmodel",
            name="art_list",
            field=models.ManyToManyField(
                related_name="exhibition", to="art.artmodel", verbose_name="작품리스트"
            ),
        ),
    ]
