# Generated by Django 4.1.1 on 2022-09-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0007_alter_artmodel_name_alter_artmodel_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artmodel",
            name="image",
            field=models.FileField(null=True, upload_to="uploads/art/"),
        ),
        migrations.AlterField(
            model_name="artmodel",
            name="size",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="사이즈"
            ),
        ),
    ]
