# Generated by Django 4.1.1 on 2022-09-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0008_alter_artmodel_image_alter_artmodel_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artmodel",
            name="image",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
    ]
