# Generated by Django 4.1.1 on 2022-09-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_artistmodel"),
    ]

    operations = [
        migrations.RemoveField(model_name="artistmodel", name="birthday",),
        migrations.RemoveField(model_name="artistmodel", name="phone_number",),
    ]
