# Generated by Django 4.1.1 on 2022-09-10 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_artistmodel_birthday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistmodel",
            name="birthday",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^?([0-9]{4})-?([0-9]{2})-?([0-9]{2})$"
                    )
                ],
                verbose_name="생일",
            ),
        ),
        migrations.AddField(
            model_name="artistmodel",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$"
                    )
                ],
                verbose_name="연락처",
            ),
        ),
    ]
