# Generated by Django 4.1.1 on 2022-09-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_artistmodel_birthday_artistmodel_phone_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="artistmodel", name="birthday",),
    ]
