# Generated by Django 4.1.1 on 2022-09-10 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_artistmodel_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistmodel",
            name="birthday",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^([0-9]{4})-?([0-9]{2})-?([0-9]{2})$"
                    )
                ],
                verbose_name="생일",
            ),
        ),
    ]
