# Generated by Django 4.1.1 on 2022-09-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_artistmodel_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistmodel",
            name="email",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="이메일"
            ),
        ),
    ]
